//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vita
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actividad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Actividad()
        {
            this.ActividadUsuarioAnotado = new HashSet<ActividadUsuarioAnotado>();
            this.Evento = new HashSet<Evento>();
        }
    
        public int id { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public Nullable<int> edadMinima { get; set; }
        public Nullable<int> edadMaxima { get; set; }
        public Nullable<System.DateTime> fechaActividadComienzo { get; set; }
        public Nullable<System.DateTime> fechaActividadFin { get; set; }
        public Nullable<int> cantidadDias { get; set; }
        public Nullable<int> precio { get; set; }
        public Nullable<int> cantidadParticipantes { get; set; }
        public Nullable<int> categoriaId { get; set; }
        public Nullable<int> subcategoriaId { get; set; }
        public Nullable<int> localidadId { get; set; }
        public Nullable<int> entidadId { get; set; }
    
        public virtual Entidad Entidad { get; set; }
        public virtual SubCategoria SubCategoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActividadUsuarioAnotado> ActividadUsuarioAnotado { get; set; }
        public virtual Categoria Categoria { get; set; }
        public virtual Localidad Localidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Evento> Evento { get; set; }
    }
}
