//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vita
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actividad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Actividad()
        {
            this.EventoActividad = new HashSet<EventoActividad>();
            this.ActividadSegmento = new HashSet<ActividadSegmento>();
            this.UsuarioInscriptoActividad = new HashSet<UsuarioInscriptoActividad>();
        }
    
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
        public int EdadMinima { get; set; }
        public Nullable<int> EdadMaxima { get; set; }
        public Nullable<int> Precio { get; set; }
        public System.DateTime FechaDesde { get; set; }
        public System.DateTime FechaHasta { get; set; }
        public Nullable<int> CantidadDias { get; set; }
        public int CantidadCupo { get; set; }
        public int CategoriaId { get; set; }
        public int SubcategoriaId { get; set; }
        public int LocalidadId { get; set; }
        public Nullable<int> UsuarioId { get; set; }
        public byte[] Foto { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventoActividad> EventoActividad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActividadSegmento> ActividadSegmento { get; set; }
        public virtual SubCategoria SubCategoria { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioInscriptoActividad> UsuarioInscriptoActividad { get; set; }
        public virtual Categoria Categoria { get; set; }
        public virtual Localidad Localidad { get; set; }
    }
}
