//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vita
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActividadSegmento
    {
        public int ActividadSegmentoId { get; set; }
        public Nullable<int> ActividadId { get; set; }
        public Nullable<int> SegmentoId { get; set; }
    
        public virtual Actividad Actividad { get; set; }
        public virtual Segmento Segmento { get; set; }
    }
}
