//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vita
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Campos()
        {
            this.Respuesta = new HashSet<Respuesta>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> FormularioDinamicoId { get; set; }
        public Nullable<int> TipoDatoCampoId { get; set; }
        public Nullable<bool> Obligatorio { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Respuesta> Respuesta { get; set; }
        public virtual FormularioDinamico FormularioDinamico { get; set; }
        public virtual TipoDatoCampo TipoDatoCampo { get; set; }
    }
}
