//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vita
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventoSegmento
    {
        public int EventoSegmentoId { get; set; }
        public Nullable<int> EventoId { get; set; }
        public Nullable<int> SegmentoId { get; set; }
    
        public virtual Evento Evento { get; set; }
        public virtual Segmento Segmento { get; set; }
    }
}
