//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vita
{
    using System;
    using System.Collections.Generic;
    
    public partial class FechasActividad
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> FechaDesde { get; set; }
        public Nullable<System.DateTime> FechaHasta { get; set; }
        public Nullable<System.DateTime> LunesHorario { get; set; }
        public Nullable<System.DateTime> MartesHorario { get; set; }
        public Nullable<System.DateTime> MiercolesHorario { get; set; }
        public Nullable<System.DateTime> JuevesHorario { get; set; }
        public Nullable<System.DateTime> ViernesHorario { get; set; }
        public Nullable<System.DateTime> SabadoHorario { get; set; }
        public Nullable<System.DateTime> DomingoHorario { get; set; }
        public int ActividadId { get; set; }
    
        public virtual Actividad Actividad { get; set; }
    }
}
