//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vita
{
    using System;
    using System.Collections.Generic;
    
    public partial class Necesidad
    {
        public int id { get; set; }
        public string descripcion { get; set; }
        public int eventoId { get; set; }
        public int habilidadId { get; set; }
    
        public virtual Evento Evento { get; set; }
        public virtual Habilidad Habilidad { get; set; }
    }
}
