//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vita
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Actividad = new HashSet<Actividad>();
            this.Evento = new HashSet<Evento>();
            this.UsuarioInscriptoActividad = new HashSet<UsuarioInscriptoActividad>();
            this.UsuarioCategoriaElegida = new HashSet<UsuarioCategoriaElegida>();
            this.UsuarioInscriptoEvento = new HashSet<UsuarioInscriptoEvento>();
            this.UsuarioSegmento = new HashSet<UsuarioSegmento>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public Nullable<int> SexoId { get; set; }
        public Nullable<int> Dni { get; set; }
        public string Email { get; set; }
        public Nullable<int> LocalidadId { get; set; }
        public Nullable<int> Celular { get; set; }
        public Nullable<int> Telefono { get; set; }
        public string UsuarioName { get; set; }
        public string Pass { get; set; }
        public string SitioWeb { get; set; }
        public string SobreMi { get; set; }
        public Nullable<int> RolId { get; set; }
        public byte[] Foto { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Actividad> Actividad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Evento> Evento { get; set; }
        public virtual Localidad Localidad { get; set; }
        public virtual Rol Rol { get; set; }
        public virtual Sexo Sexo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioInscriptoActividad> UsuarioInscriptoActividad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioCategoriaElegida> UsuarioCategoriaElegida { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioInscriptoEvento> UsuarioInscriptoEvento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioSegmento> UsuarioSegmento { get; set; }
    }
}
