//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vita
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioInscriptoEvento
    {
        public int EventoId { get; set; }
        public int UsuarioId { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        public virtual Evento Evento { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
