//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vita
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VitaEntities : DbContext
    {
        public VitaEntities()
            : base("name=VitaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Actividad> Actividad { get; set; }
        public virtual DbSet<ActividadUsuarioAnotado> ActividadUsuarioAnotado { get; set; }
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<Colaborador> Colaborador { get; set; }
        public virtual DbSet<Entidad> Entidad { get; set; }
        public virtual DbSet<Evento> Evento { get; set; }
        public virtual DbSet<Habilidad> Habilidad { get; set; }
        public virtual DbSet<Localidad> Localidad { get; set; }
        public virtual DbSet<Necesidad> Necesidad { get; set; }
        public virtual DbSet<PartidoDepartamento> PartidoDepartamento { get; set; }
        public virtual DbSet<Provincia> Provincia { get; set; }
        public virtual DbSet<SubCategoria> SubCategoria { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
